<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Contact Form Submission</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8fafc;
        }
        .header {
            background: linear-gradient(135deg, #10b981, #065f46);
            color: white;
            padding: 30px;
            border-radius: 12px 12px 0 0;
            text-align: center;
        }
        .content {
            background: white;
            padding: 30px;
            border-radius: 0 0 12px 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        .message-box {
            background: #f0fdf4;
            border-left: 4px solid #10b981;
            padding: 20px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .detail-row {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 12px 0;
            border-bottom: 1px solid #e5e7eb;
        }
        .detail-row:last-child {
            border-bottom: none;
        }
        .label {
            font-weight: 600;
            color: #374151;
            width: 30%;
        }
        .value {
            color: #6b7280;
            width: 70%;
            text-align: right;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #6b7280;
            font-size: 12px;
            border-top: 1px solid #e5e7eb;
            padding-top: 20px;
        }
        .btn {
            display: inline-block;
            background: #10b981;
            color: white;
            padding: 12px 24px;
            border-radius: 6px;
            text-decoration: none;
            font-weight: 600;
            margin: 20px 0;
        }
        @media (max-width: 600px) {
            .detail-row {
                flex-direction: column;
                align-items: flex-start;
            }
            .label, .value {
                width: 100%;
                text-align: left;
            }
            .value {
                margin-top: 4px;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 style="margin: 0; font-size: 24px;">📧 New Contact Form Submission</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">A message has been received through the contact form</p>
    </div>

    <div class="content">
        <div class="message-box">
            <h3 style="margin: 0 0 10px 0; color: #065f46;">Message Details</h3>
            <p style="margin: 0; line-height: 1.8;">{!! nl2br(e($contact->message)) !!}</p>
        </div>

        <div style="margin: 30px 0;">
            <div class="detail-row">
                <span class="label">Subject:</span>
                <span class="value">{{ $contact->subject }}</span>
            </div>
            <div class="detail-row">
                <span class="label">From:</span>
                <span class="value">{{ $contact->name }}</span>
            </div>
            <div class="detail-row">
                <span class="label">Email:</span>
                <span class="value"><a href="mailto:{{ $contact->email }}" style="color: #10b981; text-decoration: none;">{{ $contact->email }}</a></span>
            </div>
            <div class="detail-row">
                <span class="label">Phone:</span>
                <span class="value">{{ $contact->phone ?? 'Not provided' }}</span>
            </div>
            <div class="detail-row">
                <span class="label">Preferred Contact:</span>
                <span class="value">{{ ucfirst($contact->contact_method) }}</span>
            </div>
            <div class="detail-row">
                <span class="label">Submitted:</span>
                <span class="value">{{ $contact->created_at->format('M d, Y \a\t h:i A') }}</span>
            </div>
        </div>

        <div style="text-align: center;">
            <a href="{{ url('/admin/contacts/' . $contact->id) }}" class="btn">View in Admin Panel</a>
        </div>

        <div class="footer">
            <p>This message was automatically generated by Ipswich Mosque Contact System</p>
            <p>Submitted from: {{ url('/') }}</p>
        </div>
    </div>
</body>
</html>